version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: maestro_inventario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"  # Puerto externo 55432, interno 5432

  backend:
    build: ./backend
    ports:
      - "8000:8020"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/maestro_inventario
      SECRET_KEY: inventario-maestro-inventario-secret-key-123456789abcdef
      DEBUG: true
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data:
