"""Fix warehouse relationships

Revision ID: a4fbc6569610
Revises: d3cf3b29a2a1
Create Date: 2025-07-06 00:20:09.224560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4fbc6569610'
down_revision = 'd3cf3b29a2a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
